CREATE TABLE [dbo].[Users] (
 [Id] INT PRIMARY KEY,
 [Name] NVARCHAR(50) NOT NULL,
 [Email] NVARCHAR(50) NOT NULL,
 [Password] NVARCHAR(258) NOT NULL,
 [BirthDate] DATETIME NOT NULL,
 [RegisterAt] DATETIME NOT NULL 
);