CREATE TABLE [dbo].[WorkItems](
	[Id] INT PRIMARY KEY,
	[Name] NVARCHAR (50) NOT NULL,
	[Priority] NVARCHAR(7) NULL,
	[Comment] NVARCHAR(15),
	[ScheduleDay] DATETIME,
	[CreatedAt] DATETIME NOT NULL,
	[ProjectId] UNIQUEIDENTIFIER NOT NULL ,
	[SubTaskId] UNIQUEIDENTIFIER
);